<?php
/**
 * PHASE 10 — Bulk Insert Learners
 *
 * Inserts ~500 learners with staggered registration dates
 * (one per day, starting from today going backwards).
 *
 * Visit: https://smartmathconner.co.tz/database/insert_learners_bulk.php
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once __DIR__ . '/../php/db_connection.php';

echo "<pre>\n";
echo "=== BULK INSERT LEARNERS ===\n\n";

/* ----------------------------------------------------------------
   All learner full names (in order — first = today, last = oldest)
   ---------------------------------------------------------------- */
$fullNames = [
'ADELA DAUDI WAPALILA','JESCA JULIUS KISANGA','JENIPHA BARAKA MWANDE','SWABRA AWADHI SANTAFI',
'KERRYFOST POLIKARP MWACHA','LIGHTNESS GODFREY URASSA','ANJELA GODFREY MROSSO','JERUMANA EFRAIMU TARIMO',
'PRINCESS INNOCENT URIO','JUDITH PATRICK MARK','EMMANUAL AMAN TEMBA','JUNIOR GODFREY MOSHI',
'SASHA DEVID MACHANGE','BARAKA KIDA TARIMO','CHARLES GODFREY CHARLES','KULFU RAMADHANI MAPUNDA',
'MARTHA PIUS MROSO','DONALD GENES MASSAWE','SARA FREDRICH NDAMKA','MELISA CHARLES MWALULU',
'AISHA SAIDI MSANGI','GLORY ELIHURUMA KOWERO','VERONIKA DEVID SHAYO','EPIFANIA JANUARY MSEKE',
'DEBORA VICTOR NDUNGURU','GLADNESS JASON MTUI','JOAN RAMADHAN MZIRAY','STERIA SAIMON DOMA',
'FARAJI FADHILI RAMADHANI','QUEEN GODLISTEN MLAY','KAREN WALES MBALEKELE','ITHANI OMBENI KAAYA',
'PASCALINA EDWARD NGOWA','PRINCE INNOCENT LEMANGWA','WiNIFRIDA RAFAEL KAPINGA','DORCAS TYSON TEMBA',
'JOLING WILIAM MAINGE','SARA SEBASTIAN WILIUM','DANIEL JAPHET ENYASI','MAGRETH ANDREA KAVISHE',
'MWANAIDI HAMISI ISMAEL','DORCAS ATHUMAN MKUBWA','JORDAN WILFRED MINJA','EMMANUEL EDIMUND UISO',
'ANWARI ABUTWAA MCHANA','MUNAWARI SALUM KONGA','NEEMA SEBASTIAN WILUMI','WITNESS FLUGENCE TESHA',
'JOHNSON SIMON MWANJALA','REHEMA EMANUELI SUMAYE','JOVIN RAFAEL TARIMO','ABDULRAHMAN YUSUFU MLAYA',
'NURATH MOHAMED SEMBE','FRANCIA PETER MREMA','HELEN DAVID MSOELO','IRENE REGINALD SHIRIMA',
'CHRISTINA PAULO SHENGANI','HANSON KIVUMA MWITA','ENJOY ALEX NGOI','DERICK BERNARD SAMU',
'THERESIA RICHARD NZINGA','ETHAN ANASEL LYMO','MWANAISHA JUMA MWAMPASIKE','PHIDELIS ADOLF MOREMBO',
'EVALINE EMMANUEL SHIRIMA','EMMANUEL VICTOR MSAU','VERONICA GEORGE MLAY','IDDY RUBEN MSHANA',
'NADIA ABDUL MRISHO','ANJELA DENIS MKENDA','DENIS CHRISTOPHER MUINDI','JOAN DEOGRATIAS TARIMO',
'HUMAIYA HARID TUPE','RAMADHAN BENJAMIN','DANIEL THOMAS LAIBAINGUTI','JONAS GOODLUCK YOHANA',
'INNOCENT FRED','ABDULRAHMAN RAMADHAN RAMADHAN','REGINODI REGAN NDOSI','ABRAHAMAN RAMADHAN MSUMBIJI',
'SARAFINA CHARLES MHINDI','ELIA LAURENCE KIONDO','SHEDRACK PETER MTENGO','DORCAS PETER MSAU',
'DIANA DICKSON MTARI','VIVIAN FRANK KIMARIO','WILIAM PAULO KOMBO','GODBELSS SELEMAN MGAMBA',
'ESTER ANOLD MASAULE','LATIFA ABDALLAH ZUZE','AHMAD WAZIRI MOHAMED','NEEMA SAMWEL MBANDO',
'ASHA JUMA FERUSI','HELEN EVANCE LYMO','BRIGHTNESS APOLINARY MAIGE','DANIEL JEREMIA MKOMA',
'PIUS PETER','YUSRA ZUBERI MGAMBA','GENOFAVA DEODAT MUI','NADIA ANTONY MDEE',
'RAYMOND JOSEPH KIMARIO','ERICK DEOGRATIUS MARANDU','DEBORA JAFET MMARI','DASTAN ENOCK NDEKIRO',
'ELIA THOMAS SIRILI','JOSHUA SALIMU MKURUGUTA','AGUSTINO DEOGRATIAS KIMARIO','REWARD FRANK MRINGO',
'EDSON MAMBO MUYOMBO','SAUMU RASHID SHEMNGA','BAHAT JONAS MWAMBANGA','KELVIN TADEY TARIMO',
'JOSEPH EPIFAN JOSEPH','AMINA AMANI HAMISI','JOEL EPIFAN MLOKA','IBRAHIM RAMADHANI',
'MARIUM ELIAS KIVEAN','FARHAT SHABAN MALIZA','PAUL OBED PAUL','FAUSTA ELIUDI KIRAGO',
'JACQULINE GABRIEL MARTIN','VIVIAN FLORID STANSILAUS','SHEDRACK DONATUS MWAKASIGA','IRENE RODRICK EVAREST',
'ROSEMARY LORRY MTIMBA','ZAMHA ABUBAKARI IDDI','ELIZABETH SIMON','JENIFA JULIUS ELIAMLIS',
'FRED WILIAM PATRICK','ESTER GODWIN LEONARD','PRISCA GABRIEL PROTAS','ADELA KIBERA',
'ISACK LUGANO ALEX','AMINA ABDUL','RUTH PAULO PHILIPO','JANETH AGUSTINO CHRISTO',
'ISACK WILSON GODFREY','BRIGHTNESS CITHBETH','QUEEN ABEL OMAR','ROSEMARY DUKILA IDIL',
'JOHNSON DICKSON','HAMZA SAIDI ALLY','AILAT GEOFREY CRISTIAN','ANOLD AGUSTINO',
'VIOLA AMEDEUS BEDA','NEEMA AMOS SAIMON','BRIGHTNESS GOODLUCKY MOLLEL','NASRI ISMAEL HASSAN',
'EVETA DENIS MATHIAS','KELVIN JULIUS SENZIA','QUEEN ERASTO KITOMARI','DORCAS JACKSON SABAYA',
'MICHAEL JACKSON MICHAEL','LIDYA ANOLD SAIMON','ROSEMARY MUSA JAMUHURI','MOSSES EMANNUEL GEORGE',
'DEBORA CLEMENT ERIEL','FATUMA RAJABU IDDI','NEEMA NOEL ELIATOSHA','RIZIKI UWESO RAMADHANI',
'JAMES GEOFREY CHRISTIAN','BILAS DOGRATIUS BILAS','JOSEPH NESTORY PETER','NASMA SALIMU ABDUL',
'MAURINE SAID ALLY','YUSUPH HASHIMU YUSUPH','OMARY TWAHIL OMAR','GLORY JOSEPH PETER',
'MARRY SAMWEL DONALD','LIZZBETH NICODEMAS MULI','ANJELISTA CHRISTOPHER JAPHET','FATNA RAZAK ABAS',
'JOSEPH LAURENT JUMA','AITHAN RAYMOND TADEI','SOFIA SHARIFU HAMIS','GENOFEVA RICHARD MOSSES',
'HAIDAN RICHARD MOSSES','SADICK ABDUL','MOHAMED AMAN MOHAMED','BRIGHTNESS CHRISTOPHER EDWARD',
'COLLING GODLISTEN JACKSON','JOHNSON DULL SEMBUA','RAMADHANI BILAL BALEJUSA','BENEDICTA PETER EXPERANCE',
'ISAYA JOSEPH JUMANNE','ALEX GODLISTEN INYASI','BRIYTON SULLE DAVID','MARIETA FELIX EPIGOD',
'SWALAF HARUNA SALIMU','KHAIRATI HAMAD ADAM','IRENE SAMWELI JOHN','DERICK ABDUL MAJALA',
'ANJELINA SADOT BWEZELILA','ANJELA SIMON FRANCIS','BEATRICE ZUBERI RAMADHANI','ISACKA BENJAMIN FILIPO',
'CAREEN WISTON MICHAEL','JOHN CHRISTOPHER PHILIPO','RAHMA BARAT IDD','BONIFACE JEREMIA BONIFACE',
'AJIRA SHABANI ISSA','JOHN ENOCK','BRIYTON GOODLUCK MOLLEL','VANESSA ENNOCENT',
'ASHURA SALIMU ZEPHANIA','JESCA PAULO HERIEL','JESCA PETER DAMIAN','EMMANUEL DISMAS ERNEST',
'ZUHURA ABDALAH NASRI','MAURINE EMADODI ELISANTE','JOSHUA JACKSON AKOKO','JOEL GOODLUCK PANTALEO',
'MESHACK ZAKARIA TADEY','DAUDI PATRICK NDIKI','JOHN JAMES JUMA','ELIA GIDION BAZIL',
'FILIPO PATRICK PHILIPO','ISAYA FADHILI ISAYA','ELIA DISMAS DAUDI','ELISHA ROBERT HERIEL',
'HASSAN RAMADHAN HAMIDU','ANJELINA SHABANI ISSA','CHRISTINA JOSEPH','FATUMA SHAIBU OLEA',
'FATMA AMANI SAIDI','JOYCE STEPHANO PAULO','MARY ANDREA BARAKA','SWABRINA RASHID WAZIRI',
'SIFAEL JUMA SAMWELI','GLORIA JUSTINE JOFREY','FLORENCE REVOCAT FLORENCE','NICODEMUS GODFREY PRISCUS',
'RAHEL MATHIAS ABDALA','VIVIAN EMMANUELI LYANGA','MUHAMMED ALLY SELEMAN','GLORIA ROBERT EDWAD',
'NOEL MUSA SAID','ASHIRAFU HAMAD HUSEN','SARAFINA JOSEPH PIUS','FEITH BERNAD BARIK',
'NASRA RASHID KIBWANA','LIGHTNESS GODBLESS SHAYO','NOELA JAPHETH','RAHMA IDDY',
'SAMIA SALE HE SHABAN','MRISHA SAIMON MSOFE','DICKSON TYSON TEMBA','JOSEPH ERASMI AKILIMALI',
'REGINALD FILBERT PHILIPO','FALHAT SELEMAN SAID','NELSON FILEX MUSHI','RAHEL ISAYA DONALD',
'DIANA EMMANUEL JUSTINE','CAREEN LUCA EDWARD','BRAYSON CHARLES','RIHANA SAMWEL BARIKI',
'PILI JUMA NASRI','LILIAN EDWARD ANDREA','GIAN ALBERT OTENGA','HAIRIA FAUKA OMARY',
'VALERY MGHOI SHIRIMA','SHANI GODFREY PROSPER','ANUARY MUHAMED AMOR','ADRIANA PASCHAL GERALD',
'ISMAEL MIKDAD ISMAIL','MARIAMU JUMA MUHAMED','DOREEN JESEPH PETER','JACLINE FRANK INYASI',
'DANIEL MSECHU DEOGRATIUS','YAPHET NDERINGO SHEDRACK','SAMWEL EVANCE MARO','CHRISTOPHER OSWARD TESHA',
'HAULAT AMANI MUHAMED','NAOMI CHRISTOPHER JOHN','ABDULKARIM MUHAMMED IBWAKA','CLARA DAUD JOHN',
'ALIAS SHABAN','CONSOLATA FILEX JOHN','VANESSA FRANSIS MARTIN','RAHMA SHABANI BAKARI',
'ALLY ADAM MASOMO','DOMINICK GENES MASSAWE','JOVIN ELIKANA PETER','EDINA DANIEL MARTINI',
'JACKSON PETRO DAMIAN','ISMAEL MUHAMMED RAMADHANI','RAFAEL MICHAEL SEKIBAHA','GRACE EMMANUEL MGONDA',
'VAILETH HENRY MFUNE','JENIPHA LAURENC FLORENC','ABDALAH TWALIB SAID','MAURINE ZAKARIA THADEI',
'AQUELINE BONEVENTURE OISO','SELINA AMANI BAKARI','LIGHTNES EMANUEL LYMON','KULUTHUMU JAMALI ATHUMANI',
'HEAVENLIGHT EMANUELISHEPHASDONI','EMANUELI MICHAEL NJAU','VISENT HENDRY OBEDI','LIDYA JAMES MAGONJA',
'GUSTAF ERNESTI','GLADNESS JULIUS ANAELI','MARY HASSAN RAMADHANI','ALLYMAYUNGA MASHAKA',
'JOSEPH SILVESTA GASPER','IRENE FRED KOM','GODWIN FESTO LAMECK','FRENK FILEX',
'MAURINE MTUA JULIUS','MESHACK YOHANA PATRICK','ERICK CHARLES LEKEY','HELENA ALEX MUSHA',
'JOYCE PAULO TEMBA','NAJMA ELIAS RAMADHANI','IRENE ATHUMANI','BLESSING BONEFANS JOHN',
'FRED FRANSIS SIMA','ESTER GASPER FILIPO','HANS EVANS BENSON','BAKARI SELEMANI IDDI',
'BRAYSON SELEMANI IDDI','OMBENI ARKADI MSHABAA','AGNESS GODLUCK JONAS','HANS RAMADHANI IDDI',
'DAVID TUMAINI SAGARAY','BRIGHTALEN','NORAH ELIMADODI MKENDI','GRAYSON GODRICH LERINGA',
'YUSRA HASSAN BASAN','ESTER PAUL JOSHUA','ESTER GABRIEL ASSENGA','BRAYSON ROBATH LYIMO',
'FURAHA EVANSI STANIFOPHOD','MESHAK DANIEL MGAMBA','SUSAN SIMON ABEL','TWAIBA ROBERT THADEO',
'EMANUEL MODEST MSUYA','KELVIN WALESI GUSTAFU','MULHATI MAULID MKOLA','ELISHA KAJITANI MASHA',
'PETER HENDRY ASENGA','ELIZABETH INNOCENT TARIMO','IZACK SANITY JOSEPH','CAUTHAN ABUTWALIB WAZIRI',
'QUEEN JULIAS MSHANA','MACKLIMILIAN BRUNO MASALANGA','MSAFIR IBRAHIM SALIMU','RAJABU HASSAN SHEKAPEMBA',
'MOSES MONGELA KITUNDU','ZENAICE REGINALD SHAYO','JOAN AMIN KIMARO','DANSON SAMUEL SAM',
'GIFT EMANUEL MOSHI','PETRONILA PETER MSAU','MIKAEL SAMWEL PETER','CAREEN GODSON MAWALA',
'YUSUFU GIDION LAIZA','MIKAEL STEPHANO GADIELI','FURAHA ZEBADIA LYIMO','EMANUEL FREDY JOHN',
'NASMA BASHIRI APAI','DAVID WILLI KITUWA','IBRAHIM MWENDO JACOB','EVAGREEN DENIS BANZI',
'JASMINI YUSUFU ABDALLAH','JAZILA IBRAHIM SHABAN','ALLEN OVER URIO','HUSSEN ABDILLAH MNYANJOKA',
'MESHACK MOHAMED NGWAMBI','ELIZABETH ALBERT SHIRIMA','JULIANA GERVAS OLSKO','DEBORA FILES MMBANDO',
'AGREE ROBERT MKUGO','NEEMA DAMAS LELO','WEMA ROMANI KIMARO','BARAKA SHABANI BAKARI',
'NOTIBRUGA HONEST KAWISHE','EMANUEL ERASTO SHIRIMA','FRANCIS FLORIN KAUKI','REGINALD DEOGRATUS ALFRED',
'JOIN HUMAN SATORI','SAMIRI SWALEHE SAID','JOSEPH PETRO CHAMBILO','EERNEST DISMAS ERNEST',
'DAVID WILIAMU MUSHI','AMEDEUS RODRICK MUSHI','PREYGOD LEONARD NJAU','IJUMAA SELEMANI BAKARI',
'DANIELI EMANUELI MOSHI','DAVID JOSEPH NGOO','ROSE JOSEPH MWATIKE','AYUBU HAMFREY MACHA',
'GRACE GALLERY MASAWE','MAURIN JOSEPH NDOLO','BRYAN BONIFAS MAYUNGA','CLARA SAFAR BAHA',
'BITRESI GIDION MAWALA','SHABAN MTUKU MUYOMBO','SHEDRAK DANIEL KIMU','ANDRIANO AMEDEUS MUSHI',
'EMMANUEL BENJAMIN NGILA','I SACK EMANUEL MUSHI','OMARI MUSHI SHIKAPOMBE','SAMSON SIMON ASSENGA',
'RICHIE PENUEL MDUMA','REHEMA OMBENI NKO','RAUNZWA RAMADHAN JUMANI','RACHEL SELEMANI RAMADHAN',
'SABRINA YASIN MIRAJI','IBRAHIM PAULO KALO','JOSHUA PROSPER TARIMO','LAILATU RAMADHAN MAGOMBE',
'DOMITILA JOSEPH TOMAS','AGNESS ATHUMAN SHABANI','RAHMA IBRAHIM RAJABU','BRAYSON JOSEPH NDOLO',
'SHABANI JUMA SHABANI','BRYAN OSCAR PREYGOD','JENIFA GERALD MOSHA','PETER DAMASI ASSENGA',
'MARTHA JONAS MTUI','GLORY FESTO LEONAD','MWANAASHA SHABAN RASHID','AMINA RASHID KASM',
'ALPHONCE SAID MKALI','MESHACK GENES','MAUREEN GILBERT KAVISHE','NEEMA JACKSON KIMBI',
'DANIEL DONATH SHIRIMA','MAGDALENA JULIUS MTUI','AIZACK ZENAS KAWISHE','BENSON ERICK KISHIWA',
'AGNES ATHUMAN SHABANI','EMANUEL SIFAEL GEORGE','EBENEZA CONSTANTIN ALEX','NAOMI GRADO SAMWEL',
'TARIQ SHABANI SELEMANI','SIA PAUL AUGUST','ALBERT ROLLY NYAKARERE','MAURINE ISSAWANGU ELIAMRINGI',
'VANESA VICENT MOBA','EMMANUEL JOSEPH NEMES','AISHA SALIMINI SWALEHE','JOSHUA YONA JOHNSON',
'JOSHUA ALLY HASSAN','FATINA FADHILI JUMA','JOSHUA JOHNSON PETER','DOREEN DAMIAN BALTAZARY',
'JOSHUA SANGITO JOSEPH','CAREEN DEO TARIMO','ZAINABU ABUTWAA JUMA','BAKARI ALLY BAKARI',
'AISHA SHAFII SHABANI','SHAMSUDINI TWALIB SAID','GILIBERT EVANCE MARICELY','MARIA ELIUDI KIRANGO',
'HIGHNESS RICHARD MOSES','CAREEN OMBRNI AFITWA','CINTHIA CHIFU','CHARLES RICHARD EMMANUEL',
'JANETH PAULO CLAUS','BARAKA GABRIEL SOLLY','JUDITH PAUL','MISHELI WILLIAM PHILIP',
'YASRI HALID JUMA','MILKA SAMORA JOSEPHAT','TRIFINIA NICHOLAUS VENANCE','JOSEPH EVANCE EVELINE',
'DENIS FRANK JUMA','SWALEHE RAMADHAN SHABANI','JUNAIYA JUNAIDA ABRAHAMAN','GRACE BARAKA GODFREY',
'RACHEL SAMSON RICHARD','QUEEN NICHOLAUS ABELI','THURAYYAN ABUTWAHA SAID','MAXIMILIAN BRUNO THADEI',
'MARIA JOSEPH JOHN','ANOLD GEORGE TENGA','CHRISTOPHER EMMANUELI ADAM','ABDULKADIRI KIKA ABED',
'IRINE ELIA INYAS','MODEST EDWARD ALOYCE','AMINA WAZIRI ABEDI','EZEKIEL STEPHANO KLAUDY',
'TECLA RODRICK RICHARD','EMMANUELI JOSEPH JUMANNE','EMMANUELI ONESMO SEVERINE','ELISHA ADOLFU KOMBO',
'KIMWAGA MUHIDINI HAMIS','GLORY HERMAN SAMWEL','NANCY ROMAN SHIRIMA','EMILIANA HENDRY SILAYO',
'AMANI EVANCE STANPHOD','ROSE NDOLO JULIUS','CAREEN ROMAN JOHN','DENIS MELKIAD MMBANDO',
'WINNIE NICHOLAUS ABELI','VAILETH GODFREY ATHUMAN','SAMWELI FREDRICK GUSTAPH','ANGELA SEBASTIAN MODEST',
'NASRA ELIAS SHABANI','FABIAN FORTUNATUS JEREMIA','GILIBERT SEBASTIAN ADOLFU','MARIAM WAZIRI HASHIM',
'BARAKA ERNEST','ANTHON ANOLD SIMON','ANDREA JAMES RAPHAEL','EBENEZA FILEX HAPPYGOD',
'JACKSON JACOBO ANDREA','TWARIKI AMIRI KHALID','VAILETH GASPA URIO','QUEEN SIXTUS KILIANI',
'PETER ISHUMAIL PETER','ELISHA DANIEL RAMADHAN','ELISHA ABIUD ESTOMIHI','JACKLINE ELIATOSHA CHARLES',
'PAULO ROLLY NYAKARERE','KELVIN DAUDI TIMOTHEO','DANIEL JOSEPH NGOO','IBRAHIM FESTO MASASHUA',
'JENIPHER GODSON LEMWEL','FLORA ALEXANDRA PAULO','GLORY GODSON JOHN','BERTHA ALFRED FAUSTINE',
'IBRAHIM TYSON ANAEL','CAREEN LUTHER GEORGE','LIGHTNESS ELIA INYAS','ESTA ANDREA KIMAIO',
'NATHAN ISACKWIPSON','JOSHUA EZRA JOSEPH','CLARA PETER WISO','BLESSING CHARLES MARTIN',
'GLORY JACKSON MTUI','VERONICA JOSEPH AUGUSTINO','JESCA ADOLF SEBASTIAN','CLEMENTINA SATURINE ANSELIMU',
'ANNA PETER KIPARA','VANESSA SELESTINI LAURENCE','OMARY MAJID ISSA','DIANA SYPRIAN GABRIEL',
'GLORIA GODWIN LEONARD','LUCKMAN SHAFII HAMIS','NASRA PROCHES FLORENCE','LIGHTNESS ANTHONY',
'RABIA MUBARAKA JUMA','ANJELA GODBLESS JOHN','JOSEPH PAULO KALUKITH','BRAYAN MICKDAD SWAI',
'BEATRICE PETER JACKSON','EMMANUELI NICKSON MICHAEL','NOELA NICKSON PROTAS','JOSEPHINA CHARLES CHANGARUCHA',
'EZEKIA PHILIPO TLEMI','J0YCE MUHAMMED BAKARI','BRAYAN DANIELI EZEKIEL','ESTER JOHN SHIRIMA',
'RAHELI JOEL MOLA','ALICE BETUELI RUBEN','SELEMANI YUSUPH ABDALA','FATMA RAZACK ABASI',
'ANETH COSMAS FAUSTINE','JAMES JACOBO','BACKLINE NELSON PETER','CATHERINE FLORID STANSLAUS',
'JAPHET ANJELIUS SHIRIMA','YASINI HAMISI ABDALA','FRANCE JOSEPH','PETRO MARTINI MGHAMBA',
'LUIZA GILIBERT MODEST','JOHNSON EVANCE MARO','SWABAHA HARUNA SALIM','JACKSON NELSON PETER',
'EMMANUEL BONIPHACE AROBOGAST','IMRANI SAID','ISAYA ELIA SHIRIMA','PHILIPO JAMES PHILIPO',
'MUHAMED OMARY MUHAMED','JUNIOR ALEX SIMBA','GLADNESS JOHN','NASRI ELIASA SHABANI',
'MUSA JOHN MOLEL','ERICK GODFREY AROBOGAST','GRACENEEMA ALEX SILAYO','ABDI RASHIDI OMARI',
'ABDI HUSSENI SHELUKINDO','ABDULRAZACK NURUDINI MSUMARI','ABUBAKARI SEPH KIPINGU',
'ABUBAKARI KARIMU SEIKARI','ADAM ZUBERI ZUBERI','AIVAN CHARLES DHAHABU','AKRAM HILARY NGONYANI',
'ALAWI HIJA KASIMU','ANIFA RAMADHANI ABDALA','ARAFA ISIHAKA SHEMBIU','ASHA OMARI SEMKIWA',
'ASHURA AMIRI MASHINA','ASIA ABUBAKARI ZUBERI','ATHUMANI ARAPHAT LIMBEGA','AYMAN BAHATI YAHAYA',
'BATUILI KOMBO FUNDI','BENSON EMMANUEL SINGA','BRAYAN KAIZA MWETA','BRAYANA MUSA MWIKOLA',
'CAREN ALBERT KIMARO','DAMALISI DASTAN MGONDA','DORCAS NOVATUS KIMARIO','ERICK SAMWEL SINGANO',
'FARHIYA BAKARI SEKIYONE','FATINA TWALIK ABDALLAH','FATUMA ALFANI SHEHONDO','FATUMA HASSANI JAMANDA',
'FATUMA IDDI KOMBO','FATUMA MNKANDE FARAJI','GABRIEL MICHAEL UGUU','GLORY JOSEPH MTANGI',
'GLORY ISSA ALLY','HAAJIRI JUMAA MJATA','HADIJA MIRAJI JUMA','HADIJA FADHILI SHEMHILU',
'HADIJA ABDALLAH MUSSA','HALFANI MUSSA MSHUZA','HAMIDU YASINI MSHUNGA','HAMISI ALAWI KIWAYO',
'HANIFA RAMADHANI ATHUMANI','HAPSA OMARY KIPURI','HAULA BAKARI ALLY','HAWA ZUBERI KIBONA',
'HERIETH PHILIP RAJABU','HIJRA HEMEDI MBOWETO','IBRAHIM ABUBAKAR VICENT','IBRAHIMU ABUBAKARI NGOLA',
'IKRAM SPIA MWAIMU','ISMAIL SUFIAN MWENJITU','IVAN ELISANTE SHENDADA','JACKSON PAUL MWAMBONEKE',
'JENISTA JOHN CHEKWAZE','JOHNSON YUSUFU MHINA','JOSHUA GURISHA ELIESIKIA','JUDITH JOHN PACHANGA',
'JUMA BIAS OMARY','JUMA ABDALLAH KIURA','JUNIOR EDWIN MTEI','KHALID FRANK MSAGATI',
'KHAUTHAR MOHAMED NASORO','KUDRATH MBARAKA MANGALA','KURUTHUMU NURU ZUBERI','LATIFA RAMADHANI LUKAYO',
'LILIAN MARTINE MBILU','LOOKMAN JAFARY KINDENGE','LUKAIYA FEDHILI KIFEA','MAHADI MSHANGASHO MUSA',
'MAIRA RAMADHANI SHEKIMWERI','MARIAMU IDRISA MUSA','MUDASILI ABDALLAH SHELUKINDO','MUHAMADI OMARI MCHAGI',
'MUHAMADI MUSA KANIKI','MURSHID ZAHARANI MAKAU','NAGERITY JUMA KATUMBO','NAJMA JAFARI NKULO',
'NASIRA SHABANI MSALI','NASRA ABDALLAH CHAHUWILE','NASREEN YASINI MTANGI','NAYFAT ABDALLAH MZITU',
'NOREEN IRIGO TOGOLANI','NUFAIRA JUMA HIMILI','NUKAIRA JUMA HIMILI','NURATH SALMINI SEKIONDO',
'NURDIN NASIBU BUDU','NURDIN SALIMU MAIVU','NURHAT MANENO CHUNDU','NURIATI SHADRACK SHEMFUMBWA',
'NUSRATH SALMINI SEKIONDO','NUSRATH MOHAMEDI MKOMWA','PATIENCE LEWIS SEMBOGO','PRECIOUS PETER KIVI',
'PRISCA FABIAN MASHAKA','PRISCILA SAMWEL MWAIMU','RAHIMU ABDALLAH MNKANDE','RAIYANI MOSSES MADALE',
'RAJABU ISMAIL MTANGI','RAMADHANI ISSA KIZUMBE','RAMADHANI ANDALLAH SHEKIBULA','RAUFU ABIRAI OMARI',
'RAYMOND EDWARD WILLIAM','REBECA ANDREA KAISAVENA','REDISIANA EMMANUEL SHAMBALAI','REHEMA AHMED MAGOGO',
'REHEMA ABEDI SELINGO','REHEMA AHMED SAIDI','ROSE YANAZA MCHOMVU','RUJAINA ATHUMANI OMARI',
'RUMAISA ERICK KIVUGO','RUMANITHA ATHUMANI SABUNI','SAHIL ABUU MPIKAMNO','SALHA YUNUS KIMANGU',
'SALIM OMARI SHUI','SALMA OMARI BARUA','SALMA ADAM KARATA','SALMIN HOSSIN NYAMUKORO',
'SAMIA JAMALI NGUZO','SAMIA OMARI MUSA','SAMIA JUMA KILONGA','SAMIA JAMAL NKAYA',
'SAMIR MOHAMEDI AMIRI','SAMIRA SELEMANI MWAMBANDE','SAUMU MIKIDADI SHEMFUMBWA','SHABANI YUSUFU BARAZA',
'SHEDRACK RAMADHANI SALIMU','SHEYNA ALIADI MBOKO','SUHAIRA BARAKA SHEMBILU','SUMAIYA HASSAN SEIKERA',
'TALK SHABAN KIFUNTA','UMAIRA HUSENI HAMIDU','UMMULKHAIR JAMALY SHEMAHONGE','WALLACE JOSEPH SAMWEL',
'WAZIRI RAJABU MNJAMA','WILSON LUCAS SAMWEL','WINFRIDA EMANUEL LEKULE','WITNESS WILLIAM GUDEN',
'YAKOBO CHRISTOPHER MWAMKAI','YASIRI OMARI CHOKA','YASRI OMARI BAISI','YUSUPH AYUBU NGOMELO',
'ZAKATI JUMA MDEE','ZALINA SHABANI MWAGILO','ZUBEDA SADIKI MTUNGAKOA','ZUHURA NAWABU NURUKANI',
'ZULUBEIFAT JUMA TANDIKO','RABIA AHMEDI YASINI','REBECA ANDREW MGENDWA','FAHADI ADAM MSABAHA',
'LOVENESS SAFIEL CHAMBUA','REDISIANA EMANUEL SHAMBALAI','NURATH MANENO CHUNDU','GODLUCK BARAKA TUVAKO',
'NAJMA JAFARI MKULO','NSIRI FURAHINI ELIENEZA','CALVIN ELIATOSHA NNKO','NANCE BAROSHE SHEKUMKAI',
'FEISAL NURDINI NGOLE','ZUHURA SALIM MALIKI','FORTUNATA EMANUEL KIBULA','BARAKA SELEMANI ABDALLA',
'JACOBO DONVAN DASTANI','RAHMA HAMISI SHABANI','CHRISTINA GEORGE WITIKA','NURATH MUSSA MOHAMED',
'BRITANI BENSON CHELANGO','MWANAMVUA MOHAMEDI ZUMO','STEVEN ALEN SHEMSHASHU','HUDHAIFA SALEHE ALLY',
'SAMEER ABDULHAMID DAFFA','SAMIRI MAHAMUDU NGANGA','HIJIRATI HAJI ALLY','MUDATHIR ALLY DARUS',
'YUNUSI MUSTAFA MALIKI','SALMA ADAM KARATA','NILAN SELEMANI','LUQUMANI RAMADHANI MDOE',
'MUNIRI ABUBAKARI MAKWAYA','PATRICIA EMANUEL MGAZA','ELIZABETH SAMSON MWACHENGO','ALISIA STUWART MASANJA',
'ESTER MARTINI KILALO','AMIROSE ABDALLA JUMA','NASRA SADIKI HEMEDI','HAUSEN TURABI SALIM',
'STEVEN NELSON NTABAHULU','VIRDAN RAFAEL MJEMA','JOVIN ISAYA HERSON','NURATH SHEDRACK SHEMFUMBWA',
'NATASHA SHABANI CHIKILA','ARAFA KASIM KANJU','ROSEMARY GEOFREY MGAYA','ALISIA STUWART MASANJA',
'EMANUELA EMANUELCHARLES','ELIZBETH LUCAS MADEGHE','JUNIOR MUSSA OMARI','RUJAINA ATHUMANI FATIHU',
'HAMIDU YASINI MSHUNGA','VICENT PETER JAFARI','YUSRA DAUDI CHAMSHAMA','MORIS DOMINIC LEVIRA',
'MARIAM RASHID MUYA','YUSRA JAMAL SHEBUGHE','JONSON JOSEPH MUHUTO','ABUBAKARI DAUDI KWAVI',
'MOHAMED ABED IDD','ELIA SADAM UKULU','MORIN HAMISI ABDALLAH','HIJIRAT RAMADHANI MSANGI',
'SUHAIBU SELEMANI SAIDI','REHEMA AHAMAD MAGOGO','YASIR OMARY CHOKA','JUSTINI GEORGE MTUNGUJA',
'ISLAM YAHAYA MANGULUKO','HAMISI RAMADHANI MDOE','NESTORY MARWA MANGONI','LILIAN STEVEN MDOE',
'SAMWEL PASCHAL JIRANI','HILMI MOHAMED MBWEGO','SHABANI BINURU LUBWAZA','NUSRATH MOHAMED MKOMWA',
'NURATH HOSENI CHOBO','ANAIVANA HAMPHREY NURUSO','GLADNESS JOSEPH KIJA','ZUHURA NAWABU NURUKANI',
'TARIKI SHABANI KIFUMA','SAMIA OMARI MUSSA','RUJAINA MIKIDADI SHEMFUMBWA','ZUBEDA SADIKI MTUNGAKOA',
'LAILA RAMADHANI SWABUNI','MAHAMUDU HALIFA MBILIKILA','ABDULRAZAKI JUMANNE MBUYA','KELVIN DANIEL NOYA',
'DAVID PETER MPEMBA','BALILE EMANUEL','BRAYANA MUSSA MWIKOA','LUQUMANI JAFARI KINDENGE',
'SALHATI YUNUS KIMANGU','SAMIRI MUSTANI HAMISI','YUSRA BASHIRILUZEGEA','AISHA KIJANGWA MMBUGU',
'HAFSA OMARI ABDALLA','TARIKI MIRAJI JUMA','AKDANI JAMEEL MOHAMED','MUSTAFA SADIKI AMBANYONGE',
'JANETH JOHN SELEKI','IKRAM SHAFII SHECHAMBO','ZAHARA BAKARI OMARI','NURATH HAJI CHAMBO',
'AKRAM SAID JUMA','JOYCE JOHN NDEHA','NAJMA RAMADHANI SHEMTOI','IKRAM TWAHIRU SEMBE',
'FEISALI RASHID MSHAHARA','BAKARI MIRAJI MUSSA','REHEMA ABED ATHUMANI','JAFARI MALINDI IBRAHIM',
'IKRAM MBARAKA MWENGELE','NARMANI KASIM JUMA','SAMIRI SHEDRAKI SHEMFUMBWA','SHARIFA MOHAMED MMBANDO',
'EDISON EDWIN MTEI','ALEX OSCAR MROPE','IBRAHIM HEMED MDOE','ABUBAKARI DAUDI KWAVI',
'RUMAISHA ERICK KIVUGO','SALMA MUSTAFA MOHAMED','JACKSON GAUDENCE KWEMBE','AMINA ABDALLAH SHEDAFA',
'MOHAMED KOMBO FUNDI','NAHID TUPA FARID','RAHMA JUMA KIZITO','MARY WALES JORDAN',
'HAMISI ALAWI KIWAYO','SALMINI HOSEIN NYAMUKORO','JOSHUA PAULO MSOKA','FIRIDAUS ABDALLA BURO',
'KRISENSE KIBWANA RAJABU','JACKLINE DASTANI MHINA','NASIRI HARUNA ZUBERI','FEISALI MOHAMEDI MBELWA',
'IVANI GODFREY CHALANGE','RAUFU ERICK KIVUGO','HUBAIDA MBARUKU DOLE','SUMAIYA OMARI MUSA',
'GLORY STANLEY SEBWAGE','OMARI ISLAM','MUDATHIR JUMANNE GEORGE','SUGHAILA BARAKA SHEMBILU',
'ZARINA SHABANI MWAGIRO','GRESS THOBIAS KITENA','LIGHTNESS DITO CHENGULA','SWAHIBU RAMADHANI KIPANDE',
'MORISON OSCAR MALEBETO','OMARI ABDALAH YAMBI','ISLAM ALLY KIHIYO','SAIDI KASIM SANGOMA',
'FATUMA AHAMED','NASRA SADIKI HEMEDI','NURDINI LUGE KANJU','WALES PAULO JOHN',
'RUKAIYA HABIBU RAJABU','LOVENESS EMANUEL NYEKEGETI','HEAVEN M NICHOLAUS','KELLIN KIBWANA RAJABU',
'TWARIBU RAMADHANI','ALLY RAJABU SABUNI','ELIZABETH MICHAEL','LAILA RAMADHANI SWABUNI',
'RAMADHANI ALLY ZUBERI','PASCHAL EMANUEL LIMO','WAZIRI RAJABU MNJAMA','ABDULKARIM ISSA KIMITU',
'SAMIRA SELEMANI MWAMBANDE','AIKAN NARBET SANGA','HADIJA AMANI MSEKWA','IBRAHIM PONSIASO MASAWE',
'ROSE EMANUEL BONIFACE','SAUMU EMMANUEL MOSHA','YASINTA HEBERT KWAI','BRAYTON GODFREY SHELUTETE',
'JAMILA RAJABU HOSENI','JACKLINE STEVEN MSUYA','UMYKHAIRA YAHAYA SHENKOME','LAURENT JAMES MGANGA',
'NOELA EMMANUEL LEKULE','YUSRA MUSTANI MSOKA','ARTHUR ANDREA MBANO','NASRA SALIMU SHEMAHIMBO',
'EMMANUEL MARTIN SHEMANGODA','VINICIUS KELVIN KIKA','RAHMA ISSA MDOE','GEORGE STEVEN MWAIMU',
'AMIRI KASSIMU RAMADHANI','ISSA SEFU MADENI','VAILETH JOSEPH MAYILA','MINHAJI ISHAQA MBWELWA',
'SHADIA HIJA NYUMBA','IBRAHIM WILLIUM ALFRED','HAIRATH RAMADHANI IDDI','YASINI MUSSA MSHANGUZO',
'SHAKILA MOHAMEDI KISIJU','ABDALLAH ZUBERI MAGAMBO','NURAT JAHA BARUA','NEEMA ISSA MBONEA',
'HAFIDHI ISSA MWAMBO','NEYLA MOHAMED MSHITI','ARAFAT OMARY NKAMA','HIPTIHAM SHABANI KIMWAGA',
'FRANSIS GODFREY KIMARO','KELVIN JOHN MANONA','ASIA FADHILI ATHUMANI','MOREEN KELVIN KOMBA',
'NAILA HANSI MFINANGA','COLIN COSMAS JUSTIS','IJUMAA MUSSA MWAMBAKA','SALHA SHABANI SHEKABUGHE',
'FEISAL ALI KATOMALI','KELLY RAMADHANI HASSAN','ABDULKADIRI RAMADHANI LUZEGEA','KHAIRATH SHABAN JUMBE',
'SALHA ASHIRU SENYARI','JESCA ELIAS MAYALA','WINFRIDA ZEPHANIA SAMWELY','JUSTINE BALTAZAR KAVISHE',
'ASIA MUSA ABDALA','BRIGHTON LAWRENCE MDOE','SHABANI JUMANNE MBUYA','LAMLATI JUMA SAMCHELO',
'ZULFAT RAMADHANI HOZA','DENNIS ALBERT KIMARO','THURAYYAH ZAHRAAN MBAGA','LUQUMAN SAIDI MTALI',
'KUDRAT BENSON MWANGI','NAGMA RAMADHANI MWANANGOTO','YUSRA AMRANI ISSA','JOSPH ELIYA KHERI',
'BRIGHTNESS LAWRENCE MDOE','OMARI HASANI MWAFEDA','KHAIRATH AHMED DADY','SAMIA IBRAHIM ALLY',
'YUSRA RASHIDI SHEBURUZA','ABDULKAREEM MADABA SULU','ALADIN NURDIN NYENGA','SELEMANI AMIRI SINGO',
'FRANSIS ANDREW MGANGA','JIBRI KHALID GUMBO','OMARI RAMADHANI MAKASI','BRAYTON JOHN CHARLES',
'MIKIDADI MAKANGE SHEHE','TWAHLATH ZUBERI SAID','FREDY AMANI GABUNGA','AMINA OMARY NGWAZIKO',
'LUQMAN MWINJUMA MTANGI','IBRAHIM JAFARI SHEHOZA','HARUNA RAJABU BAKARI','YASIRI JUMA AMIRI',
'AMRIA AMIRY MBUGUNI','DUSTAN EMMANUEL KARATA','WARDA RAJABU OMARI','JUMA RAMADHANI ZAHABU',
'ELISHA SELEMANI MRUTU','NAWABU RASHIDI KISOME','ABDULRAZACK OMARY NKAMA','NAJMA ABDUL MHANDO',
'BRAYTON ISACK CHAMWILE','FEISAL SHAFII WAZIRI','HUMAIRA KARIM IDDI','SHADIA DAUDI MSENGA',
'RAHMA ABEDI MAJALIWA','ALFANI OMARY KIONDO','JAFARI ABDALLAH CHEPE','RAMADHANI RAJABU NGODA',
'JOYCE MARTIN MBILU','JENIPHER MKAMI CHACHA','ERASTO ROMAN ISAKA','JOSEPH ATUPELE MWANDOLA',
'IKRAM YUNUS NGOLLA','PETER DANIEL MTUNDA','NAIFATH NURUDINI RASHIDI','IKRAM OMARI SEMKIWA',
'KELVIN MICHAEL KANIKI','HULIGYAN ATHUMANI TWAHA','SHALON GEORGE HAULE','SUMAIYA SHUKRA TUPA',
'SABRINA SAID ABDALLAH','MAURINE ALBERT TETE','RAUHIA RASHID KISARAZO','MERY RAMADHANI MKWIZU',
'JONATHAN ALFRED KAWAMALA','TIMOTHY TUMAINI MUGISHA','ILHAM JUMA ABDALAH','OMARI SHOSI OMARI',
'LIDYA ISAAC WILLIAM','NANCY BARAKA MALATA','CAREEN ABDALLAH SEMBOJA','IVAN AMEDEUS KAVISHE',
'GLORY THOBIAS KITENA','LIGHTNESS OMBENI MSHANA','ARAFA HARUN KIMARO','JOTHAM JOHN MAKAJI',
'FAHIM ABBAKARY MSELULA','SUHAILA SHABANI BASHIRU','ABEDNEGO YOHANA SEMBE','YUSRA IDRISSA KILUWASHA',
'NADYA MUHSINI KUSAGA','NAJMA IBRAHIM ABDALLAH','GLADNESS JACKSON KOWERO','OMARI ALLY OMARI',
'FAIDHATI SALIMU MNUA','NUHAIRAT RAMADHANI KIBAYA','FIRDAUSI TWAHIBU SINGANO','NASRA IBRAHIM JAWAZI',
'ANNUARI RASHIDI RAMADHANI','ISLAM JAFARI HAMZA','VIVIAN STUART DAFFA','AHLAM SAID MSUYA',
'ESTER FRANK WILFRED','HAIRATH ABDALA KIULA','HAYTHAM ATHUMANI MSHANA','EDITHA MARIUS MPINGA',
'HADIJA RAMADHANI ZAWIA','JOSEPH ALOYCE FRANK','ABRAHAM JAMEEL BAABADI','IVAN ERASTO MBAGO',
'LAURA YUSUPHU SWAI','IKRAM ISSA JUMA','JOVIN ADIL MLILINGWA','ATARAH ALBRIGHT MACHAKU',
'EMMANUELA LUPIANA HARE','BUTHAYNA RASHID SHELUKINDO','JORDAN JOSEPHAT NDEGEYA','HANIPHA HAMZA KILONGO',
'MAIGE AZIZI MAIGE','RAISA FRANCE MALYA','AIDAN PETER LUHANDA','JOACHIM WILSON ISHICA',
'GARVIEL ERICK MGATA','ARYA EDSON MUSHERUZI','JARDON JAMES SIWALE','AHMET AZIZI SABUNI',
'AIKA HERBERT MUSHI','ABDULHASSAN OMARI MHANDO','NAYLAH NESTORY NDOKOLE','IMRAN CHAMBA MAREGESI',
'JOVANNA JOSEPH KOMBA','CAREEN MSHANGA MANGACHI','NIMRATI NURUDIN SINDA','CAYLAN DAVID CALVIN',
'GODFREY ELTON ADO','BEILLAH BARAKA HASSAN','GIANNA JAMES','ALVINA SEVERINE KIMAKA',
'BRAYAN D MAHIMBO','JEREMIAH PENIEL EDWARD','EDRIAH PETER MHINA','ABIGAIL J HAMARO',
'CAREEN CHARLES','GENEVIER HAROUN','FARHIYA J DUNGAMARO','REHEMA K RICHARD',
'MUKHFARY E MJATA','MERYNE K MROSSO','LYAM W KIMARO','LIAM W KIMARO',
'IDRISA J NGEREZA','ELIYA T KUSAGA','FIDELIS S KITAMBULIO','FEISAL S SEVULI',
'COLLINE J ZACHARIA','BRIGHTON EDWARD','AYUBU K MAGANDYA','ZAITUNI SAID SAMZIGWA',
'ANGELA LAUREAN LIVINUS','HAYRATH HATIBU JONGO','MELYN KONDRAD MROSSO','FADHILA I. KIZEGELI',
'NAJMA D. MSELEMO','DORCAS NOVATUS','SYLIVIA MSOFE','HANCE LINUSI MSACKY',
'FARISH AZIZI CHALLAH','ARIELLA FRED KAPOTA','ASMA ALLY KANIKI','EMMY MAJALIWA TUMAINI',
'PAULA AMONI MZALALILA','OMARY ABASI OMARY','CLINTON NOLASCO MLAY','JAYLEEN JOSEPH NTEGA',
'REBECA ZACHARIA MNKAI','PRECIOUS PHARES RENATUS','COLLIN EDWARD NTILIKINGWA','FRANCIS NTUGWA MAKULA',
'DIANA SHUKURU BANZI','CLANCY DAVID MRUTU','ROSHAN ABDULMANAFFI MSOFE','FAHAMUNI ERNEST FUNGO',
'ZAHEERYDIN SAIDI MKUFYA','MWAJUMA HASSAN RAJABU','SLIM SHABAN YUSUPH','MUSTAPHER NAJIM SHIMANGWE',
'PATRICK JACOB CHARLE','JAYDEN FRANCIS SHAYO','NOELA JULIUS MADU','ROBBIN JOSEPH NANYARO',
'NAJMA OMARY SHEMOKA','SAMIA HAMADI SHEMOKA','THEOPHIL JAPHETY MALYA','SADICK ALLY SHEKIMWELI',
'QUEEN GERALD MSAGATI','SOSTENES EMMANUEL MAGESA','KRINTONY FABIAN KAYOKA','SAJRAT OMARY MNONDWA',
'NATHAN ALBETO MKUVASA','ISSA SALIM SHEKIONDO','VIVIAN KIKWEMBE MBITA','HILDA WILLIAM NDAMBWE',
'PRECIOUS AMONI MZALALILA','LORMAX MUSSA JAMES','LINTON NOLASCO MLAY','JOEL PAUL NGODA',
'ZENITH SELEMANI BAWJI','CHRISTIAN CLEOPHAS MAGESA','SIRAJI HAMIS MNGURUTA','NOEL FANUEL MAGEMBE',
'SAGAFI SWALEHE MSUYA','NANCY BAROSHE SHEKUMKAI','ROMMY IBRAHIM KANIK','EDIMUND GAMA LUPINDO',
'MUZNA MOHAMEDI MUSTAFA','ASHAT SAIDI LIKO','RAKEEM RASHID IDD','NOLLAN GODFREY MGOO',
'HARIS DAUDI MZIRAY','MOSSES CORNELIUS LEMA','CLARICE CLEMENT WILSON','IAN LUKAS KAMANDA',
'FEISAL HASSAN SHAMBALAI','ELISHA EGIBATH KABOGI','FEISAL JUMANNE DAFA','RAPHAEL HUMPHREY NGOWI',
'AUDREY CEDRIC MAJAWA','NIGEL MARK MAKWINYA','ALVIS ALFRED LETARA'
];

$total = count($fullNames);
echo "Total learners to insert: $total\n\n";

/* ----------------------------------------------------------------
   STEP 1: Generate learner data
   ---------------------------------------------------------------- */
echo "--- STEP 1: Generate learner data ---\n";

$today = new DateTime('2026-07-12');

/* Get next available username number */
$maxNum = $database->fetchOne(
    "SELECT COALESCE(MAX(CAST(SUBSTRING(username, 12) AS UNSIGNED)), 0) as max_num
     FROM users WHERE role = 'learner' AND username LIKE 'SMART/chil/%'"
);
$nextNum = $maxNum ? ((int)$maxNum['max_num'] + 1) : 1;
echo "Starting username number: SMART/chil/" . str_pad((string)$nextNum, 3, '0', STR_PAD_LEFT) . "\n";

$learners = [];
foreach ($fullNames as $i => $fullName) {
    $fullName = trim($fullName);
    if (empty($fullName)) continue;

    /* Parse name: first word = first_name, rest = last_name */
    $parts = preg_split('/\s+/', $fullName, 2);
    $first_name = $parts[0];
    $last_name = $parts[1] ?? '';

    /* Clean up weird chars */
    $first_name = preg_replace('/[^a-zA-Z\s]/', '', $first_name);
    $last_name = preg_replace('/[^a-zA-Z\s]/', '', $last_name);
    if (empty($first_name)) continue;

    /* Username */
    $username = 'SMART/chil/' . str_pad((string)$nextNum, 3, '0', STR_PAD_LEFT);
    $nextNum++;

    /* Random password */
    $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    $password = '';
    for ($p = 0; $p < 8; $p++) { $password .= $chars[random_int(0, strlen($chars) - 1)]; }
    $hashed = password_hash($password, PASSWORD_DEFAULT);

    /* Claim code: KH-XXXXXX */
    $codeChars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    $claim_code = 'KH-';
    for ($c = 0; $c < 6; $c++) { $claim_code .= $codeChars[random_int(0, strlen($codeChars) - 1)]; }

    /* Date: today minus i days */
    $regDate = clone $today;
    $regDate->modify("-{$i} days");
    $dateStr = $regDate->format('Y-m-d');

    $learners[] = [
        'username' => $username,
        'first_name' => $first_name,
        'last_name' => $last_name,
        'password' => $password,
        'hashed' => $hashed,
        'claim_code' => $claim_code,
        'date' => $dateStr,
    ];
}

echo "Generated " . count($learners) . " learner records\n";
echo "Date range: {$learners[0]['date']} (today) → " . end($learners)['date'] . " (oldest)\n\n";

/* ----------------------------------------------------------------
   STEP 2: Insert into database
   ---------------------------------------------------------------- */
echo "--- STEP 2: Insert into database ---\n";

$inserted = 0;
$errors = 0;

foreach ($learners as $learner) {
    try {
        /* Check for duplicate username */
        $exists = $database->fetchOne("SELECT user_id FROM users WHERE username = ?", [$learner['username']]);
        if ($exists) {
            echo "  SKIP: {$learner['username']} ({$learner['first_name']} {$learner['last_name']}) — already exists\n";
            continue;
        }

        /* Check for duplicate claim code */
        $codeExists = $database->fetchOne("SELECT user_id FROM users WHERE claim_code = ?", [$learner['claim_code']]);
        if ($codeExists) {
            /* Regenerate claim code */
            $codeChars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
            $learner['claim_code'] = 'KH-';
            for ($c = 0; $c < 6; $c++) { $learner['claim_code'] .= $codeChars[random_int(0, strlen($codeChars) - 1)]; }
        }

        /* Insert with explicit created_at */
        $database->execute(
            "INSERT INTO users (username, password, role, first_name, last_name, claim_code, claim_code_created_at, created_at, is_active)
             VALUES (?, ?, 'learner', ?, ?, ?, ?, ?, 1)",
            [
                $learner['username'],
                $learner['hashed'],
                $learner['first_name'],
                $learner['last_name'],
                $learner['claim_code'],
                $learner['date'] . ' 08:00:00',
                $learner['date'] . ' 08:00:00',
            ]
        );

        $inserted++;
        if ($inserted % 50 === 0) {
            echo "  ... inserted $inserted so far\n";
        }
    } catch (Exception $e) {
        $errors++;
        echo "  ERROR: {$learner['first_name']} {$learner['last_name']} — " . $e->getMessage() . "\n";
    }
}

echo "\nInserted: $inserted\n";
echo "Errors: $errors\n\n";

/* ----------------------------------------------------------------
   STEP 3: Verification
   ---------------------------------------------------------------- */
echo "=== VERIFICATION ===\n";

$totalLearners = $database->fetchOne("SELECT COUNT(*) as c FROM users WHERE role = 'learner'");
echo "Total learners in database: {$totalLearners['c']}\n";

$todayCount = $database->fetchOne("SELECT COUNT(*) as c FROM users WHERE role = 'learner' AND DATE(created_at) = '2026-07-12'");
echo "Registered today (2026-07-12): {$todayCount['c']}\n";

$oldest = $database->fetchOne("SELECT MIN(DATE(created_at)) as oldest FROM users WHERE role = 'learner'");
echo "Oldest registration: {$oldest['oldest']}\n";

$recent = $database->fetchAll(
    "SELECT DATE(created_at) as reg_date, COUNT(*) as cnt
     FROM users WHERE role = 'learner'
     AND DATE(created_at) >= DATE_SUB('2026-07-12', INTERVAL 7 DAY)
     GROUP BY reg_date ORDER BY reg_date DESC"
);
echo "\nRecent registrations:\n";
foreach ($recent as $r) {
    echo "  {$r['reg_date']}: {$r['cnt']} learners\n";
}

/* Show sample */
$samples = $database->fetchAll(
    "SELECT username, first_name, last_name, claim_code, DATE(created_at) as reg_date
     FROM users WHERE role = 'learner'
     ORDER BY created_at DESC LIMIT 5"
);
echo "\nSample (newest 5):\n";
foreach ($samples as $s) {
    echo "  {$s['username']} | {$s['first_name']} {$s['last_name']} | Code: {$s['claim_code']} | Date: {$s['reg_date']}\n";
}

echo "\n=== INSERT COMPLETE ===\n";
echo "</pre>";
